############################
# Customized ggplot2 theme #
############################

theme_ew <- function (base_size = 20, 
                      base_family = "serif") {
  theme_grey(base_size = 18, base_family = base_family) %+replace% 
    theme(
      # Serif font, larger text, more whitespace between axes and labels
      text = element_text(family = "serif", 
                          face   = "plain", 
                          colour = "black", 
                          size   = base_size,
                          hjust  = 0.5, 
                          vjust  = 0.5, 
                          angle  = 0, 
                          lineheight = 0.9),
      axis.text = element_text(size   = rel(0.8), 
                               colour = "black"), 
      axis.ticks = element_line(colour = "black"), 
      axis.title.x = element_text(vjust = 0.4),
      axis.title.y = element_text(angle = 90, 
                                  vjust = 3),
      
      # Smaller legend with solid white background
      legend.key = element_rect(fill   = "white", 
                                colour = "white"),
      legend.text = element_text(size = rel(0.9)),
      legend.title = element_blank(),
      
      # Border around plot and slightly darker gridlines
      panel.background = element_rect(fill = "white", 
                                      colour = NA), 
      panel.border = element_rect(fill = NA, 
                                  colour = "black"), 
      panel.grid.major = element_line(colour = "gray91", 
                                      size = 0.2), 
      panel.grid.minor = element_line(colour = "gray97", 
                                      size = 0.5), 
      
      # Bolder facetting labels 
      strip.background = element_rect(fill = "grey85", 
                                      colour = NA),
      
      strip.text.x = element_text(size = 20, 
                                  face = "bold"),
      strip.text.y = element_text(size = 20, 
                                  face = "bold"),
      
      plot.background = element_rect(colour = "white"),
      
      # Larger title with more whitespace
      plot.title = element_text(size = rel(1.3), 
                                vjust = 0)
    )
}

#################################
# CSS style for knitr reporting #
#################################

sink("style.css")
cat(
  "body  {",
  "  font-family: Palatino Linotype;",
  "  font-size: 11pt;",
  "  background-color: white;",
  "  padding-top: 1em;",
  "  margin: auto;",
  "  max-width: 45em;",
  "}",
  " ",
  "  p {",
  "    padding: 0;",
  "    margin: 0;",
  "    margin-bottom: 10pt;",
  "  }",
  " ",
  "table{",
  "  margin: auto;",
  "  margin-top: 1em;",
  "  margin-bottom: 1em;",
  "  border: none;",
  "}",
  " ",
  "td, tr{",
  "  font: 10pt Palatino Linotype;",
  "  padding: 0px;",
  "  margin: 0px;",
  "}",
  " ",
  "td {",
  "  padding: 4px;",
  "  padding-bottom: 2px;",
  "}",
  " ",
  "h1, h2, h3, h4, h5, h6 {",
  "  margin: 10pt 0pt 0pt 0pt;",
  "  font-family: Palatino Linotype;",
  "  font-weight: bold;",
  "}",
  " ",
  "h1 {",
  "  margin: 24pt 0pt 0pt 0pt;",
  "  font-size: 16pt;",
  "  color: #365F91;",
  "}",
  " ",
  "h2 {",
  "  font-size: 14pt;",
  "  color: #4F81BD;",
  "}",
  " ",
  "h3 {",
  "  font-size: 11pt;",
  "  color: #4F81BD;",
  "}",
  " ",
  "h4 {",
  "  font-size: 11pt;",
  "  font-weight: bold;",
  "  font-style: italic;",
  "  color: #4F81BD;",
  "}",
  " ",
  "h5 {",
  "  font-size: 11pt;",
  "  font-weight: normal;",
  "  color: #243F5D;",
  "}",
  " ",
  "h6 {",
  "  font-size: 11pt;",
  "  font-weight: normal;",
  "  font-style: italic;",
  "  color: #243F5D;",
  "}",
  " ",
  "tt, code, pre {",
  "  font-family: 'DejaVu Sans Mono', 'Droid Sans Mono', 'Lucida Console', Consolas, Monaco, monospace;",
  "}",
  " ",
  "a:visited {",
  "  color: rgb(50%, 0%, 50%);",
  "}",
  " ",
  "pre {",  
  "  margin-top: 0;",
  "  max-width: 95%;",
  "  border: 1px solid #ccc;",
  "  white-space: pre-wrap;",
  "}",
  " ",
  "pre code {",
  "  display: block; padding: 0.5em;",
  "}",
  " ",
  "code.r, code.cpp {",
  "  background-color: #F8F8F8;",
  "}",
  " ",
  "blockquote {",
  "  color:#666666;",
  "    margin:0;",
  "  padding-left: 1em;",
  "  border-left: 0.5em #EEE solid;",
  "}",
  " ",
  "hr {",
  "  height: 0px;",
  "  border-bottom: none;",
  "  border-top-width: thin;",
  "  border-top-style: dotted;",
  "  border-top-color: #999999;",
  "}",
  " ",
  "@media print {",
  "  * {",
  "    background: transparent !important;",
  "    color: black !important;",
  "    filter: none !important;",
  "    -ms-filter: none !important;",
  "  }",
  " ",  
  "  body {",
  "    font-size:11pt;",
  "    max-width:100%;",
  "  }",
  " ",  
  "  a, a:visited {",
  "    text-decoration: underline;",
  "  }",
  " ",  
  "  hr {",
  "    visibility: hidden;",
  "    page-break-before: always;",
  "  }",
  " ",  
  "  pre, blockquote {",
  "    padding-right: 1em;",
  "    page-break-inside: avoid;",
  "  }",
  " ",  
  "  tr, img {",
  "    page-break-inside: avoid;",
  "  }",
  " ",  
  "  img {",
  "    max-width: 100% !important;",
  "  }",
  " ",  
  "  @page {",
  "    margin-top: 2cm;",
  "    margin-bottom: 1.5cm;",
  "    margin-left: 3cm;",
  "    margin-right: 3cm;",
  "  }",
  " ",  
  "  p, h2, h3 {",
  "    orphans: 3; widows: 3;",
  "  }",
  " ",  
  "  h2, h3 {",
  "    page-break-after: avoid;",
  "  }",
  "}",
  sep="\n")
sink()
